name: Release

on:
  push:
    branches:
      - "release/v*.*"

jobs:
  run-release:
    name: 'Release'
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Set version
        run: sed -i -E "s/<revision>*(.+<\/revision>)/<revision>${RELEASE_VERSION}<\/revision>/g" pom.xml

      - name: Commit version
        id: commit_version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Set version ${{ env.RELEASE_VERSION }}

      - name: Package
        run: mvn package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          target_commitish: ${{ steps.commit_version.outputs.commit_hash }}
          files: |
            ${{ github.workspace }}/core/target/mercury-core-*.jar
            ${{ github.workspace }}/http/target/mercury-http-*.jar
            ${{ github.workspace }}/pom.xml