name: Test

on:
  pull_request:
    branches:
      - "main"

jobs:
  run-test:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install artifacts
        run: mvn install

      - name: Set version
        run: |
          sed -i -E "0,/<!-- global dependencies start -->/s//<!-- global dependencies start/g" ./examples/pom.xml
          sed -i -E "0,/<!-- global dependencies stop -->/s//global dependencies stop -->/g" ./examples/pom.xml
          sed -i -E "0,/<!-- local dependencies start/s//<!-- local dependencies start -->/g" ./examples/pom.xml
          sed -i -E "0,/local dependencies stop -->/s//<!-- local dependencies stop -->/g" ./examples/pom.xml

      - name: Test artifacts
        run: mvn -f examples/pom.xml test